### ISSUE TITLE
Error: failed to open stream

### ISSUE THREAD

**Issue by hbokh** [CedricGatay/docker-koel#1]
Looking if somebody already made a container for "Koel", I found yours and it looked very usable at first.
But upon starting (`docker-compose up`) I get this error:

```
app_1 | php artisan key:generate
app_1 |
app_1 |
app_1 |
app_1 |   [ErrorException]
app_1 |   file_put_contents(/app/koel/.env): failed to open stream: Permission denied
```

Also it seems the DB remains empty (no db / tables created).
Have you managed to get this to work inside Docker yet or is it still _under construction_? Merci!

**Comment by CedricGatay** [comment]
As stated on the first commit (025f0a18671d66d08282fe042a90f95481aea5a7), one need to launch mysql then app for the first launch (so that mysql have the time to populate the initial data).

[quote]
One might need to run compose two times for the first run as the mysql instance can take time spawning or launch it with :
`docker-compose up -d db; sleep 60; docker-compose up -d app;`

This mount your media located in the ./media folder (symlink it to the proper location first)
[/quote]

**Comment by CedricGatay** [comment]
The error with env file will be fixed soon (it misses a simple chown)

**Comment by CedricGatay** [comment]
@hbokh it should be ok now if you pull

**Comment by hbokh** [comment]
Much better! Merci bien.
